module.exports = {
	name: "My Blog Site", // optional, falls back to object key
	description: "The default sites that get tested",
	options: {
		frequency: 60 * 2, // (in minutes), 23 hours
	},
	urls: [
		"https://wisnuwiry.space/",
		"https://wisnuwiry.space/tags/flutter/",
		"https://wisnuwiry.space/post/flutter-menampilkan-package-name-dan-build-version/",
		"https://wisnuwiry.space/tags/library/",
		"https://wisnuwiry.space/tags/",
		"https://wisnuwiry.space/tags/plugin/",
		"https://wisnuwiry.space/snippet/membuat-launch-url-ke-native-app-pada-flutter-menggunakan-url_launcher/",
		"https://wisnuwiry.space/tags/snippet/",
		"https://wisnuwiry.space/tags/tips/",
		"https://wisnuwiry.space/tags/firebase/",
		"https://wisnuwiry.space/series/flutter-firebase-tutorial/",
		"https://wisnuwiry.space/post/flutter-setup-firebase/",
		"https://wisnuwiry.space/series/",
		"https://wisnuwiry.space/post/pengenalan-kelebihan-dan-kekurangan-firebase/",
		"https://wisnuwiry.space/tags/bloc/",
		"https://wisnuwiry.space/post/membuat-logging-observer-pada-flutter-di-state-management-bloc/",
		"https://wisnuwiry.space/snippet/cara-build-apk-dan-appbundle-release-di-flutter/",
		"https://wisnuwiry.space/tags/localization/",
		"https://wisnuwiry.space/post/membuat-localization-flutter-dengan-extensions-flutter_intl/",
		"https://wisnuwiry.space/donate/",
		"https://wisnuwiry.space/post/cara-buat-bloc-state-management-mudah-dengan-extensions/",
		"https://wisnuwiry.space/tags/extension/",
		"https://wisnuwiry.space/snippet/cara-mudah-menghilangkan-banner-debug-di-flutter/",
		"https://wisnuwiry.space/tags/atomic/",
		"https://wisnuwiry.space/post/atomic-design-concept/",
		"https://wisnuwiry.space/tags/concept/",
		"https://wisnuwiry.space/tags/design/",
		"https://wisnuwiry.space/snippet/transparent-statusbar-flutter/",
		"https://wisnuwiry.space/post/flutter-localization/",
		"https://wisnuwiry.space/tags/cubit/",
		"https://wisnuwiry.space/post/tutorial-flutter-dynamic-theme-dengan-cubit/",
		"https://wisnuwiry.space/post/tutorial-flutter-bottom-nav-state-management-dengan-cubit/",
		"https://wisnuwiry.space/post/tutorial-membuat-infinite-load-data-dari-api-dengan-bloc-pattern/",
		"https://wisnuwiry.space/tags/editor/",
		"https://wisnuwiry.space/tags/extensions/",
		"https://wisnuwiry.space/post/rekomendasi-extension-theme-font-vscode/",
		"https://wisnuwiry.space/tags/vs-code/",
		"https://wisnuwiry.space/post/duckduckgo-webmaster-and-searchbox/",
		"https://wisnuwiry.space/tags/seo/",
		"https://wisnuwiry.space/post/alasan-kenapa-pakai-flutter/",
		"https://wisnuwiry.space/tags/dart/",
		"https://wisnuwiry.space/series/flutter/",
		"https://wisnuwiry.space/tags/blog/",
		"https://wisnuwiry.space/tags/hugo/",
		"https://wisnuwiry.space/series/hugo/",
		"https://wisnuwiry.space/post/membuat-blog-dengan-hugo/",
		"https://wisnuwiry.space/project/personal-site-portofolio/",
		"https://wisnuwiry.space/tags/personal-site/",
		"https://wisnuwiry.space/tags/web/",
		"https://wisnuwiry.space/tags/cerita/",
		"https://wisnuwiry.space/post/mulai-belajar-pemrograman/",
		"https://wisnuwiry.space/about/",
		"https://wisnuwiry.space/categories/",
		"https://wisnuwiry.space/contact/",
		"https://wisnuwiry.space/post/",
		"https://wisnuwiry.space/project/",
		"https://wisnuwiry.space/search/",
		"https://wisnuwiry.space/snippet/"
	]
};
